name: Haskell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Haskell
      uses: haskell-actions/setup-haskell@v2
      with:
        ghc-version: '9.4.8'  # Стабильная и хорошо поддерживаемая версия
        cabal-version: '3.10.1.0'

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          ~/.cabal/packages
          dist-newstyle
          .ghc
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal', '**/cabal.project', '**/cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Update cabal
      run: cabal update

    - name: Install dependencies
      run: cabal build --only-dependencies --enable-tests --enable-benchmarks

    - name: Build
      run: cabal build --enable-tests --enable-benchmarks all

    - name: Install hlint
      run: cabal install hlint --overwrite-policy=always

    - name: Run hlint
      run: ~/.cabal/bin/hlint . --report

    - name: Run tests
      run: cabal test all